language: ruby

cache:
  bundler: true


rvm:
  - 2.2
  
sudo: false

bundler_args: --jobs=3 --retry=3 --without development --without deploy

before_script:
  - bundle exec rake db:create db:migrate db:test:prepare
  
script:
  - bundle exec rspec